version: '3.8'

services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./src/database:/docker-entrypoint-initdb.d
    env_file:
      - ./dotenv_files/.env