version: '3.8'

services:
  app:
    container_name: app
    build: .
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql

  psql:
    container_name: psql
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env